# Generated by Django 3.2.3 on 2021-07-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollments',
        ),
    ]
