# Generated by Django 3.2.5 on 2021-07-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructapp', '0003_auto_20210706_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonuploads',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
