# Generated by Django 3.2.5 on 2021-07-15 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructapp', '0004_auto_20210715_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='students_enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
