# Generated by Django 3.2.3 on 2021-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructapp', '0005_alter_course_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
